### ISSUE TITLE
QWidget background settings make parts of slider disappear.

### ISSUE THREAD

**Issue by Pflo-acconeer** [pyapp-kit/superqt#252]
**Describe the bug**
QWidget settings make part of slider invisible.

**To Reproduce**
1. Copy the code from the QRangeSlider images example.
2. Add the following to the stylesheet string:
QWidget {
    background: #f8f9fa;
}
3. Run the example
4. The bar and left point of the stylized sliders will not be visible (but can still be clicked).

**Expected behavior**
The slider should still be visible even when setting QWidget background colors.

**Desktop (please complete the following information):**
Ubuntu 22.04
Python 3.10.12

**Comment by tlambert03** [comment]
Yeah, this is a known "issue", but I'm not sure how we can handle it.  Basically, there are no low-level OS primitives for a range slider exposed in Qt.  So the "tricks" we have done here to give the appearance of a native range slider is basically to draw two slider handles, and manually draw that bar in the middle.  If you override that with a custom style sheet that changes the background color, then you'll observe what you saw.  So if you want to customize parts of the slider, you will likely have to customize *all* of the slider.  See, for example, the code generating some of the custom styled range sliders here: https://pyapp-kit.github.io/superqt/widgets/qrangeslider/#screenshots

For what it's worth, the styles for range sliders are defined here: https://github.com/pyapp-kit/superqt/blob/main/src/superqt/sliders/_range_style.py ... and they live on the slider [here](https://github.com/pyapp-kit/superqt/blob/main/src/superqt/sliders/_generic_range_slider.py#L39C14-L39C20) and are applied at paint time [here](https://github.com/pyapp-kit/superqt/blob/main/src/superqt/sliders/_generic_range_slider.py#L263-L295) (among other places).  Since QSS styles override Pen styles, we clear them by default [here](https://github.com/pyapp-kit/superqt/blob/main/src/superqt/sliders/_generic_range_slider.py#L64)  ... so since QSS takes priority, when you set it manually, you override that and you'll likely need to complete the rest of the style picture by experimenting with setting `QSlider::groove:horizontal` and other things as shown in the example above

**Comment by Pflo-acconeer** [comment]
Thank you for the prompt reply! 
The immediate issue (invisible sliders) is solved by manually setting the stylesheet for the sliders. For someone coming here I had to set the background value for the Qwidget to "none" in the "override" stylesheet.

**Comment by tlambert03** [comment]
Great, I'm going to close this, since it's still not clear how we'll be able to support "partial" style sheets.  

There are indeed some pitfalls when using custom style sheets, but in most cases there is still a solution to be found with the right settings in your style sheet
